export const heroParagraph1 = 'Most of the disaster displacement recorded globally has taken place in the Asia and Pacific region. An estimated 225.3 million internal displacements—or forced movements—were recorded during 2010−2021. Large-scale storms and floods, droughts, earthquakes, tsunamis, and volcanic eruptions keep displacing millions of people every year across this vast region, that is home to most of the world’s population.';
export const heroParagraph2 = 'Many gaps in understanding the full scale and scope of displacement persist. This includes the number of people who remain displaced after disasters and the duration of their displacement. In addition, few assessments allow an understanding of the indirect and long-term social and economic impacts of displacement in the context of disasters, which hampers the design and implementation of sound policies for durable solutions and risk reduction.';
export const heroParagraph3 = 'This report aims to fill some of these gaps. It presents the disaster displacement trends in the region during 2010−2021 and provides insights into its social and economic impacts. The report also discusses the opportunities ahead, by highlighting the progress made across the region in preventing and responding to disaster displacement. It aims to serve as a basis to raise awareness of this phenomenon, encourage further investments in risk reduction and durable solutions, and guide policy toward this end.';

export const costOfDisasterParagraph1 = 'When people are displaced by disasters, they are usually separated from their capital and assets, and their ability to earn a living is often compromised. Displacement also brings with it new costs, which are borne by IDPs themselves, the communities that host them, government agencies and the humanitarian sector. These include thecost of renting temporary accommodation, and additional expenses for food and electricity incurred by those hosting IDPs in their homes. In some cases, displaced people’s income, physical or mental health, and access to education or services can also be jeopardized.';
export const costOfDisasterParagraph2 = 'The impacts of displacement on people’s livelihoods, housing conditions, health, education, security, social life and environment all have economic consequences, which can be particularly significant in the case of large-scale or protracted displacement. Despite repercussions that can stretch over years or even decades, the economic impacts of disaster displacement are largely unrecorded.';

export const wayForwardListItem1 = 'Enhance data collection and analysis on disaster displacement to systematically record the scale and severity of the phenomenon, as well as its impacts on people and economies;';
export const wayForwardListItem2 = 'Develop national policy frameworks on disaster displacement to ensure immediate, comprehensive, and inclusive support to IDPs;';
export const wayForwardListItem3 = 'Invest in the planning and financing of durable solu- tions to disaster displacement, including options for return to areas of origin, or integration in host commu- nities or other areas;';
export const wayForwardListItem4 = 'Assess the risk of future disaster displacement and its potential consequences on people and economies to develop more effective, comprehensive, and inclusive prevention plans and allocate adequate resources in vulnerable areas;';
export const wayForwardListItem5 = 'Strengthen regional collaboration on disaster displacement and foster the sharing of knowledge, experience, and expertise across Asia and the Pacific.';

export const wayForwardParagraph1 = 'Reviewing gaps in government efforts to monitor and address internal displacement helps to identify a few immediate action points to be considered across Asia and the Pacific:';
export const wayForwardParagraph2 = 'There are signs of renewed regional commitment and multi-stakeholder collaboration that could accelerate action to prevent and respond to disaster displacement more effectively. The Asian Disaster Preparedness Center and the United Nations Office for Disaster Risk Reduc- tion signed a Statement of Cooperation in August 2021 to strengthen the implementation of the Sendai Framework, promote climate and disaster resilience, and improve risk governance across Asia and the Pacific.215 Foster- ing greater accountability and monitoring and evaluating progress on internal displacement in Asia and the Pacific is key to addressing what should be considered one of the most significant challenges of the region.';

export const contactParagraph = 'IDMC\'s Global Report on Internal Displacement (GRID) is the world’s leading source of data and analysis on internal displacement Since our establishment in 1998 as part of the Norwegian Refugee Council (NRC), we have offered a rigorous, independent and trusted service to the international community. Our work informs policy and operational decisions that improve the lives of the millions of people living in internal displacement, or at risk of becoming displaced in the future.';
export const copyrightParagraph = 'Copyright © Internal Displacement Monitoring Centre (IDMC). Unless otherwise indicated, all materials on this page may be shared freely providing an acknowledgement of IDMC as the source is included. Materials may not be adapted without prior permission from IDMC.';
